### PR TITLE
get html files for different languages

### PR DESCRIPTION
**Pull request by fayland**

### CODE REVIEW

**Comment by jy-binary** [comment]
I'm not sure the public/ folder is needed - won't gh-pages then publish the pages to the URL www.binary.com/public/en/... ?

**Comment by jy-binary** [comment]
I see all the URLs are being generated on the www.binary.com and static.binary.com domains. But we'd need this compile.pl script to also work for developers in their forks. Can you make the URL paths relative?

**Comment by fayland** [comment]
I do not think url_for supports relative path. but people who forks that can change the compile.pl with domain_name => 'theirdomain.com' and run that, it will work.

**Comment by jy-binary** [comment]
Sure, that would be fine.


On Thu, Apr 28, 2016 at 9:38 AM, Fayland Lam <notifications@github.com>
wrote:

> I do not think url_for supports relative path. but people who forks that
> can change the compile.pl with domain_name => 'theirdomain.com' and run
> that, it will work.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/binary-static/binary-static-www2/pull/359#issuecomment-215282186>
>



-- 
Jean-Yves Sireau
CEO, binary.com

**Comment by fayland** [comment]
do you want to remove public? so we'll put en, zh_cn etc. lots of dir under the root dir. or you can think another name? ty

**Comment by jy-binary** [comment]
Yes, I think you can remove public, and put the en, zh_cn etc under root
directory.


On Thu, Apr 28, 2016 at 9:59 AM, Fayland Lam <notifications@github.com>
wrote:

> do you want to remove public? so we'll put en, zh_cn etc. lots of dir
> under the root dir. or you can think another name? ty
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/binary-static/binary-static-www2/pull/359#issuecomment-215285188>
>



-- 
Jean-Yves Sireau
CEO, binary.com

**Comment by fayland** [comment]
ok, moved. ty

**Pull request closed without merging**
