### PR TITLE
negar/fix_barrier

### PR DESCRIPTION
**Pull request by negar-binary**
don't change scale to show low and high barrier
show error message of waiting for entry tick if contract has started but there is no value of entry tick yet
use window.time for subscribing instead of contract's time

### CODE REVIEW

**Comment by qingweibinary** [comment]
I dont really have a good grasp on what the whole file is doing, it's pretty complex.

One thing that we can improve is to give meaningful name for conditions inside if clause ~ 
Besides that, using global var is a bad practice, using common name for global variable is even worse, eg. `window.max` and `window.chart`

**Comment by negar-binary** [comment]
@qingweibinary can we change it in a later branch? this is just to fix the current issues pending for the 100% release

**Comment by qingweibinary** [comment]
@negar-binary ;)

**Comment by jy-binary** [comment]
PLs check the cpnflicts

**Pull request merged**
